version: 2
project_name: baton-rootly
builds:
  - binary: baton-rootly
    env:
      - CGO_ENABLED=0
    id: linux
    main: ./cmd/baton-rootly
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    tags:
      - "baton_lambda_support"
dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/conductorone/baton-rootly:{{ .Version }}-amd64"
      - "ghcr.io/conductorone/baton-rootly:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=baton-rootly"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/conductorone/baton-rootly"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/conductorone/baton-rootly:{{ .Version }}-arm64"
      - "ghcr.io/conductorone/baton-rootly:latest-arm64"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=baton-rootly"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/conductorone/baton-rootly"
  - use: buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile.lambda
    image_templates:
      - "168442440833.dkr.ecr.us-west-2.amazonaws.com/baton-rootly:{{ .Version }}-arm64"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=baton-rootly"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/conductorone/baton-rootly"
docker_manifests:
  - name_template: ghcr.io/conductorone/baton-rootly:{{ .Version }}
    image_templates:
      - ghcr.io/conductorone/baton-rootly:{{ .Version }}-amd64
      - ghcr.io/conductorone/baton-rootly:{{ .Version }}-arm64
  - name_template: ghcr.io/conductorone/baton-rootly:latest
    image_templates:
      - ghcr.io/conductorone/baton-rootly:latest-amd64
      - ghcr.io/conductorone/baton-rootly:latest-arm64
checksum:
  disable: true
release:
  disable: true
changelog:
  disable: true
